version: "3.9"

services:
  web:
    build: .
    volumes:
      - .:/dragon_dungeon_arena
      - bundle-volume:/usr/local/bundle
    links:
      - postgres
      - redis
    ports:
      - '8010:8010'
    env_file:
      - .env
    command: ./bin/dev

  postgres:
    image: postgres:14.2
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:7.0
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/var/lib/redis/data

  sidekiq:
    build: .
    command: bundle exec sidekiq
    links:
      - postgres
      - redis
    env_file:
      - .env

volumes:
  postgres-data:
  redis-data:
  bundle-volume:
